Repository matrx-software/matrx, pull requests merged in 2021-05, with the labels that each got.

#294 281 arguments not passed correctly by wo
  main.py
  matrx/cases/__init__.py
  matrx/cases/bw4t/bw4t.py
  matrx/cases/bw4t/bw4t_objects.py
  matrx/cases/test_obj_arguments.py
  matrx/cases/vis_test.py
  matrx/cases/vis_test2.py
  matrx/world_builder.py
Labels: under-review

#295 Merge of #202: Use custom state throughout MATRX
  main.py
  matrx/actions/action.py
  matrx/actions/door_actions.py
  matrx/actions/move_actions.py
  matrx/actions/object_actions.py
  matrx/agents/agent_brain.py
  matrx/agents/agent_types/human_agent.py
  matrx/agents/agent_utils/state.py
  matrx/api/api.py
  matrx/cases/__init__.py
  matrx/cases/bw4t/bw4t_objects.py
  matrx/cases/logger_test.py
  matrx/defaults.py
  matrx/goals/goals.py
  matrx/grid_world.py
  matrx/logger/log_agent_actions.py
  matrx/logger/log_idle_agents.py
  matrx/logger/log_messages.py
  matrx/logger/log_tick.py
  matrx/logger/logger.py
  matrx/world_builder.py
Labels: needs-review

#299 Temp fix for #298 - double check that state in api is a dict
  matrx/api/api.py
Labels: API
